package proyectofinal;

/**
 *
 * @author Ricardo
 */
public class GUI extends javax.swing.JFrame {

    public VentanaEmergente emerg = new VentanaEmergente();
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PEMEX = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base De Datos - Papel Seguridad"); // NOI18N
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(340, 259));
        getContentPane().setLayout(null);

        PEMEX.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        PEMEX.setText("PEMEX CADEREYTA");
        getContentPane().add(PEMEX);
        PEMEX.setBounds(0, 0, 278, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/pemexlogo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 0, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PEMEX;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
